### ISSUE TITLE
subprocess32 does not have a binary manylinux1 wheel

### ISSUE THREAD

**Issue by ssbarnea** [google/python-subprocess32#60]
subprocess32 does not have a binary manylinux1 wheel, something that could speedup installation on many systems and also lower the footprint by not requiring gcc for installation.

**Comment by gpshead** [comment]
The benefit of subprocess32 comes from compiling the extension module on a modern system.  manylinux1 is too old to provide all of the necessary system and libc header APIs.  I am not going to provide a manylinux1 wheel.

Providing a manylinux1 wheel would prevent people from getting the proper benefit of subprocess32 by forcing them to use substandard fallback APIs.  This would become _the default behavior_ for most people because pip is naive enough to default to accepting a wheel when there is a perfectly good development environment that can build extension modules on the system present.

See https://github.com/google/python-subprocess32/issues/14 and https://github.com/google/python-subprocess32/issues/12 for previous discussions.

If [manylinux2010](https://www.python.org/dev/peps/pep-0571/) ever happens, that is likely recent enough to work properly.  https://github.com/pypa/manylinux/issues/179 tracks the status of manylinux2010.  By the time it is worth considering using that, Python 2 will be EOL which effectively means subprocess32 is EOL...

**Comment by ssbarnea** [comment]
I think we will see manylinux2010 quite soon as I seen more progress on it, hopefully.

**Comment by graingert** [comment]
@gpshead it actually looks like manylinux10 support is in pip already https://github.com/pypa/pip/pull/5410
